version: '3.8'

services:
  fraud-detection:
    # This will be replaced with your Docker Hub image after deployment
    image: your-username/fraud-detection-api:latest
    container_name: fraud-detection-api
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - LOG_LEVEL=INFO
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Optional: Mount logs directory for persistence
      - ./logs:/app/logs
    networks:
      - fraud-detection-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: fraud-detection-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - fraud-detection
    restart: unless-stopped
    networks:
      - fraud-detection-network
    profiles:
      - production

networks:
  fraud-detection-network:
    driver: bridge

volumes:
  logs:
    driver: local 