_wandb:
    value:
        cli_version: 0.21.0
        e:
            ntjvf6mglmt6anbfonbmhthuxem3c6bo:
                codePath: sweeps\final_model_sweep.py
                codePathLocal: sweeps\final_model_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "11.0"
                disk:
                    /:
                        total: "254855344128"
                        used: "242708598784"
                email: tommywood81@gmail.com
                executable: C:\Users\tommy\projects\auto-encoder-project\env\Scripts\python.exe
                git:
                    commit: eb99633cba9afc804bd11230c3496ccb4616f48e
                    remote: https://github.com/tommywood81/auto-encoder-project.git
                gpu: GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      name: GeForce GTX 1650
                      uuid: GPU-1fae71aa-5bd3-0913-de7a-02c43e0b27b4
                host: LAPTOP-U7F1NDJK
                memory:
                    total: "34188873728"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\tommy\projects\auto-encoder-project\sweeps\final_model_sweep.py
                python: CPython 3.11.3
                root: C:\Users\tommy\projects\auto-encoder-project
                startedAt: "2025-07-12T03:36:38.357255Z"
                writerId: ntjvf6mglmt6anbfonbmhthuxem3c6bo
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.3
            "5": 0.21.0
            "8":
                - 2
                - 3
            "12": 0.21.0
            "13": windows-amd64
model_info:
    value:
        accuracy: 0.950044286979628
        activation_fn: relu
        batch_size: 128
        best_hyperparameters:
            learning_rate: 0.01
            threshold: 99
        dropout_rate: 0.2
        early_stopping: true
        epochs: 50
        f1_score: 0.19428571428571428
        feature_count: unknown
        feature_scaling: standard
        feature_strategy: combined
        hidden_dims:
            - 64
            - 32
        l2_reg: 0.001
        latent_dim: 16
        learning_rate: 0.01
        model_path: models\final_model.h5
        model_type: autoencoder
        patience: 10
        precision: 0.6017699115044248
        random_state: 42
        recall: 0.11584327086882454
        roc_auc: 0.7286862206953392
        scaler_path: models\final_model_scaler.pkl
        sweep_hyperparameter_ranges:
            learning_rate:
                - 0.005
                - 0.008
                - 0.01
                - 0.012
                - 0.015
            threshold:
                - 95
                - 96
                - 97
                - 98
                - 99
        sweep_top_results:
            - learning_rate: 0.01
              rank: 1
              roc_auc: 0.7286862206953392
              threshold: 99
            - learning_rate: 0.012
              rank: 2
              roc_auc: 0.7281615226414413
              threshold: 99
            - learning_rate: 0.015
              rank: 3
              roc_auc: 0.7271724512909419
              threshold: 99
            - learning_rate: 0.005
              rank: 4
              roc_auc: 0.7216532135030046
              threshold: 96
            - learning_rate: 0.012
              rank: 5
              roc_auc: 0.7203752120319719
              threshold: 95
        sweep_total_combinations: 25
        task: fraud_detection
        test_split: 0.1
        threshold_percentile: 99
        train_split: 0.8
        training_date: "2025-07-12 13:36:38"
        val_split: 0.1
sweep_summary:
    value:
        best_hyperparameters:
            learning_rate: 0.01
            threshold: 99
        best_roc_auc: 0.7286862206953392
        top_5_results:
            - learning_rate: 0.01
              rank: 1
              roc_auc: 0.7286862206953392
              threshold: 99
            - learning_rate: 0.012
              rank: 2
              roc_auc: 0.7281615226414413
              threshold: 99
            - learning_rate: 0.015
              rank: 3
              roc_auc: 0.7271724512909419
              threshold: 99
            - learning_rate: 0.005
              rank: 4
              roc_auc: 0.7216532135030046
              threshold: 96
            - learning_rate: 0.012
              rank: 5
              roc_auc: 0.7203752120319719
              threshold: 95
        total_combinations: 25
