broad_sweep:
  architecture: medium
  auc_roc: 0.6834240028083378
  config:
    batch_size: 64
    dropout_rate: 0.2
    epochs: 10
    hidden_dims:
    - 128
    - 64
    - 32
    latent_dim: 16
    learning_rate: 0.001
    threshold_percentile: 95
  f1_score: 0.20040899795501022
  precision: 0.19444444444444445
  recall: 0.20675105485232068
  run_id: to7hmegg
  threshold: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    A2+Sr0815D8=
  train_loss: 0.459841787815094
  val_loss: 0.38831087946891785
final_sweep:
  architecture: final_optimized
  auc_roc: 0.6836409390182453
  config:
    batch_size: 64
    dropout_rate: 0.2
    epochs: 12
    hidden_dims:
    - 128
    - 128
    - 64
    - 64
    - 32
    - 32
    latent_dim: 16
    learning_rate: 0.001
    threshold_percentile: 92
  f1_score: 0.20030816640986132
  precision: 0.15776699029126215
  recall: 0.2742616033755274
  run_id: c8uddb8d
  threshold: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    SnD7/vPz6D8=
  train_loss: 0.5907284617424011
  val_loss: 0.5832735896110535
narrow_sweep:
  architecture: deep
  auc_roc: 0.6965920307497216
  config:
    batch_size: 64
    dropout_rate: 0.2
    epochs: 12
    hidden_dims:
    - 128
    - 128
    - 64
    - 64
    - 32
    - 32
    latent_dim: 16
    learning_rate: 0.001
    threshold_percentile: 95
  f1_score: 0.18672199170124482
  precision: 0.1836734693877551
  recall: 0.189873417721519
  run_id: i55qst7c
  threshold: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    SGihl8m87j8=
  train_loss: 0.6015559434890747
  val_loss: 0.5764695405960083
summary:
  best_overall_auc: 0.6965920307497216
  best_overall_run_id: i55qst7c
  best_overall_stage: narrow_sweep
  sweep_completion_date: '2025-07-30T19:31:22.736535'
