_wandb:
    value:
        cli_version: 0.21.0
        e:
            oxpundgkzc4cvxpli1pv1q5ic8w5bxol:
                args:
                    - --entity
                    - tommywood81-fractal-dynamics
                codePath: sweep_features_wandb.py
                codePathLocal: sweep_features_wandb.py
                email: tommywood81@gmail.com
                executable: C:\Users\tommy\projects\auto-encoder-project\env\Scripts\python.exe
                git:
                    commit: d0a19a5123b296cddc89e7e5ce6ef31f1238a67c
                    remote: https://github.com/tommywood81/auto-encoder-project.git
                host: LAPTOP-U7F1NDJK
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\tommy\projects\auto-encoder-project\sweep_features_wandb.py
                python: CPython 3.11.3
                root: C:\Users\tommy\projects\auto-encoder-project
                startedAt: "2025-07-02T02:56:42.726336Z"
                writerId: oxpundgkzc4cvxpli1pv1q5ic8w5bxol
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.3
            "5": 0.21.0
            "8":
                - 2
                - 3
            "12": 0.21.0
            "13": windows-amd64
features:
    value:
        strategy: temporal
model:
    value:
        activation_fn: relu
        batch_size: 128
        epochs: 10
        latent_dim: 16
        learning_rate: 0.001
        threshold: 95
training:
    value:
        early_stopping_patience: 5
        min_delta: 0.001
        reduce_lr_patience: 3
        validation_split: 0.2
wandb:
    value:
        entity: tommywood81-fractal-dynamics
        project: fraud-detection-autoencoder
        tags:
            - feature_sweep
