_wandb:
    value:
        cli_version: 0.21.0
        e:
            hvkremy2769omhmpfcfugqvlg9322cgb:
                codePath: experiments\feature_tuning_simple.py
                codePathLocal: experiments\feature_tuning_simple.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "11.0"
                disk:
                    /:
                        total: "254855344128"
                        used: "252080103424"
                email: tommywood81@gmail.com
                executable: C:\Users\tommy\projects\auto-encoder-project\env\Scripts\python.exe
                git:
                    commit: 67964ab1ce386cb41bdd029881dfdabacd7ad933
                    remote: https://github.com/tommywood81/auto-encoder-project.git
                gpu: GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      name: GeForce GTX 1650
                      uuid: GPU-1fae71aa-5bd3-0913-de7a-02c43e0b27b4
                host: LAPTOP-U7F1NDJK
                memory:
                    total: "34188873728"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\tommy\projects\auto-encoder-project\experiments\feature_tuning_simple.py
                python: CPython 3.11.3
                root: C:\Users\tommy\projects\auto-encoder-project
                startedAt: "2025-07-27T06:27:13.773659Z"
                writerId: hvkremy2769omhmpfcfugqvlg9322cgb
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.3
            "5": 0.21.0
            "8":
                - 2
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 32
early_stopping_patience:
    value: 10
epochs:
    value: 50
learning_rate:
    value: 0.01
random_state:
    value: 42
test_size:
    value: 0.2
