_wandb:
    value:
        cli_version: 0.21.0
        e:
            zc1elys0g2fu0s1d8tax0k40m0gj2u21:
                codePath: sweep_comprehensive_wandb.py
                codePathLocal: sweep_comprehensive_wandb.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "11.0"
                disk:
                    /:
                        total: "254855344128"
                        used: "250178052096"
                email: tommywood81@gmail.com
                executable: C:\Users\tommy\projects\auto-encoder-project\env\Scripts\python.exe
                git:
                    commit: b8ff30d5e2fdf739c46a2f6810fe7f72e7a7b697
                    remote: https://github.com/tommywood81/auto-encoder-project.git
                gpu: GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      name: GeForce GTX 1650
                      uuid: GPU-1fae71aa-5bd3-0913-de7a-02c43e0b27b4
                host: LAPTOP-U7F1NDJK
                memory:
                    total: "34188873728"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\tommy\projects\auto-encoder-project\sweep_comprehensive_wandb.py
                python: CPython 3.11.3
                root: C:\Users\tommy\projects\auto-encoder-project
                startedAt: "2025-07-08T23:19:29.988266Z"
                writerId: zc1elys0g2fu0s1d8tax0k40m0gj2u21
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.11.3
            "5": 0.21.0
            "8":
                - 2
                - 3
            "12": 0.21.0
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 25
learning_rate:
    value: 0.01
random_state:
    value: 42
test_size:
    value: 0.2
