# Baseline Autoencoder Configuration
model:
  latent_dim: 16
  learning_rate: 0.01  # Increased from 0.001
  activation_fn: "relu"
  batch_size: 128
  epochs: 5
  threshold: 95

features:
  strategy: "baseline"

training:
  validation_split: 0.2
  early_stopping_patience: 5
  reduce_lr_patience: 3
  min_delta: 0.001

wandb:
  project: "fraud-detection-autoencoder"
  entity: null  # Will be set by user
  tags: ["baseline"] 