# Baseline configuration - simplest feature set
name: "baseline"
description: "Basic transaction features only"

# Feature strategy
feature_strategy: "baseline"

# Data settings
data:
  raw_file: "data/raw/Fraudulent_E-Commerce_Transaction_Data_2.csv"
  cleaned_dir: "data/cleaned"
  engineered_dir: "data/engineered"
  models_dir: "models"
  test_size: 0.2
  random_state: 42

# Model settings
model:
  name: "autoencoder"
  hidden_dim: 64
  latent_dim: 32
  learning_rate: 0.001
  epochs: 50
  batch_size: 32
  validation_split: 0.2
  threshold_percentile: 95.0
  save_model: true

# Features to include
features:
  # Core transaction features (always included)
  transaction_amount: true
  customer_age: true
  quantity: true
  account_age_days: true
  
  # Categorical features
  payment_method: true
  product_category: true
  device_used: true
  customer_location: true
  
  # Derived features
  transaction_amount_log: true
  customer_location_freq: true
  
  # Temporal features (baseline: none)
  temporal_features: false
  behavioural_features: false 