features:
  strategy: behavioral
model:
  activation_fn: relu
  batch_size: 128
  epochs: 5
  latent_dim: 16
  learning_rate: 0.01
  threshold: 95
training:
  early_stopping_patience: 5
  min_delta: 0.001
  reduce_lr_patience: 3
  validation_split: 0.2
wandb:
  entity: null
  project: fraud-detection-autoencoder
  tags:
  - best_features
  - best_strategy_behavioral
