best_configuration:
  name: "config_05"
  roc_auc: 0.5444
  configuration:
    baseline_numeric:
      use_log_transform: true
      log_base: "natural"
      use_amount_per_item: true
      amount_per_item_offset: 1
      use_robust_scaling: true
    categorical:
      use_payment_encoding: true
      use_product_encoding: true
      use_device_encoding: true
    temporal:
      use_late_night: true
      late_night_start: 0
      late_night_end: 5
      use_burst_transaction: true
      burst_low_threshold: 0.2
      burst_high_threshold: 0.7
      use_hour_cyclical: true
    behavioral:
      use_amount_per_age: true
      amount_per_age_offset: 1
      use_amount_per_account_age: true
      amount_per_account_age_offset: 1
      use_location_freq: true
    rolling:
      use_rolling_mean: true
      use_rolling_std: true
      rolling_window: 3
    rank_encoding:
      use_amount_rank: true
      use_account_age_rank: true
      use_customer_age_rank: true
      rank_method: "average"
    time_interactions:
      use_amount_hour_interaction: true
      use_amount_per_hour: true
      use_hour_quantity_interaction: true
    demographics:
      use_age_bands: true
      age_thresholds: [25, 35, 45, 55]
      use_account_age_bands: true
    fraud_flags:
      amount_threshold: 0.8
      account_age_threshold: 90
      age_threshold: 35
      use_late_night: true
      use_high_quantity: true
      quantity_threshold: 0.9
      use_location_risk: true
      use_interactions: true
      weight_high_amount: 1
      weight_new_account: 1
      weight_young_customer: 1
      weight_late_night: 1
      weight_high_quantity: 1

all_results:
  - config_name: "config_01"
    roc_auc: 0.4889
    time_taken: 64.5
    feature_count: 36
    epochs_trained: 14
  - config_name: "config_02"
    roc_auc: 0.5011
    time_taken: 56.3
    feature_count: 36
    epochs_trained: 13
  - config_name: "config_03"
    roc_auc: 0.5370
    time_taken: 63.0
    feature_count: 36
    epochs_trained: 15
  - config_name: "config_04"
    roc_auc: 0.4902
    time_taken: 58.6
    feature_count: 36
    epochs_trained: 13
  - config_name: "config_05"
    roc_auc: 0.5444
    time_taken: 63.6
    feature_count: 36
    epochs_trained: 16

summary:
  total_configurations: 5
  successful_runs: 5
  failed_runs: 0
  average_roc_auc: 0.5123
  best_roc_auc: 0.5444
  worst_roc_auc: 0.4889
  total_time: 305.9
