seed: 42

model:
  latent_dim: 16
  hidden_dims: [1024, 512, 256, 128, 64]
  dropout_rate: 0.2

training:
  batch_size: 16
  learning_rate: 0.00005
  epochs: 5
  early_stopping: true
  patience: 25
  reduce_lr: true
  validation_split: 0.2

features:
  threshold_percentile: 85
  use_amount_features: true
  use_temporal_features: true
  use_customer_features: true
  use_risk_flags: true


