# Fraud Detection Autoencoder - Final Optimized Configuration
# This config is automatically updated when better performance is achieved

# Reproducibility
seed: 42

# Model Architecture
model:
  latent_dim: 16
  hidden_dims: [1024, 512, 256, 128, 64]
  dropout_rate: 0.2

# Training Configuration (80/20 split, no validation)
training:
  batch_size: 16
  learning_rate: 0.00005  # Fixed scientific notation
  epochs: 5
  early_stopping: true
  patience: 25
  reduce_lr: true
  # Removed validation_split since we use 80/20 split

# Feature Engineering Configuration
features:
  threshold_percentile: 85
  use_amount_features: true
  use_temporal_features: true
  use_customer_features: true
  use_risk_flags: true
  use_behavioral_features: true
  use_velocity_features: true
  use_interaction_features: true

# Best Performance Metrics (Auto-updated)
best_performance:
  roc_auc: 0.9411790625860624
  f1_score: 0.03425414364640884
  recall: 0.8266666666666667
  precision: 0.017489421720733426
  # Optimal threshold calculated for best precision/recall balance
  optimal_threshold: 1.179851
  # Model complexity info
  model_info:
    total_params: 48496
    trainable_params: 48496
  # Training history for analysis
  training_history:
    final_loss: 0.6308
    final_mae: 0.4892
    best_epoch: 5
  # Performance details
  performance_details:
    false_positives: 0
    false_negatives: 0
    true_positives: 0
    true_negatives: 0
    # Will be calculated and updated automatically
