seed: 42

model:
  latent_dim: 24
  hidden_dims: [256, 128, 64, 32]
  dropout_rate: 0.2

training:
  batch_size: 64
  learning_rate: 0.0003
  epochs: 100
  early_stopping: true
  patience: 15
  reduce_lr: true
  validation_split: 0.2

features:
  threshold_percentile: 95
  use_amount_features: true
  use_temporal_features: true
  use_customer_features: true
  use_risk_flags: true

# This config will be auto-promoted if AUC improves during final sweep
