features:
  strategy: combined
model:
  activation_fn: relu
  batch_size: 128
  epochs: 50
  latent_dim: 16
  learning_rate: 0.005  # Reduced from 0.01 to prevent overfitting
  threshold: 86
training:
  early_stopping_patience: 10
  min_delta: 0.001
  reduce_lr_patience: 5
  validation_split: 0.2
wandb:
  entity: null
  project: fraud-detection-autoencoder
  tags:
  - final_model
