inference:
  model_path: models/fraud_autoencoder.keras
  scaler_path: models/fraud_autoencoder_scaler.pkl
  threshold_path: models/fraud_autoencoder_threshold.pkl
  feature_engineer_path: models/fraud_autoencoder_features.pkl
  raw_data_path: data/raw/creditcard.csv
  engineered_test_data_path: data/engineered/test_features_90_10.csv
  test_data_sample_size: 1.0
  anomaly_threshold_percentile: 95.0
  cache_anomaly_scores: true
  predictions_output_path: predictions/dashboard_predictions.csv
  logs_path: logs/dashboard.log
features:
  threshold_percentile: 85
  use_amount_features: true
  use_temporal_features: true
  use_customer_features: true
  use_risk_flags: true
  use_behavioral_features: true
  use_velocity_features: true
  use_interaction_features: true
dashboard:
  host: 0.0.0.0
  port: 8000
  debug: false
  reload: false
