seed: 42

model:
  # Default values for config validation
  latent_dim: 16
  hidden_dims: [128, 64, 32]
  dropout_rate: 0.2
  # Architecture configurations to test (reduced to ~12)
  architectures:
    tiny:
      latent_dim: 4
      hidden_dims: [32, 16]
      dropout_rate: 0.1
    small:
      latent_dim: 8
      hidden_dims: [64, 32]
      dropout_rate: 0.1
    small_wide:
      latent_dim: 8
      hidden_dims: [128, 64, 32]
      dropout_rate: 0.15
    medium:
      latent_dim: 16
      hidden_dims: [128, 64, 32]
      dropout_rate: 0.2
    medium_wide:
      latent_dim: 16
      hidden_dims: [256, 128, 64, 32]
      dropout_rate: 0.25
    large:
      latent_dim: 24
      hidden_dims: [256, 128, 64]
      dropout_rate: 0.2
    large_wide:
      latent_dim: 24
      hidden_dims: [512, 256, 128, 64]
      dropout_rate: 0.25
    xlarge:
      latent_dim: 32
      hidden_dims: [512, 256, 128]
      dropout_rate: 0.3
    deep:
      latent_dim: 16
      hidden_dims: [128, 128, 64, 64, 32, 32]
      dropout_rate: 0.2
    shallow_wide:
      latent_dim: 8
      hidden_dims: [512, 256, 128]
      dropout_rate: 0.15
    balanced:
      latent_dim: 12
      hidden_dims: [96, 48, 24]
      dropout_rate: 0.18
    compact:
      latent_dim: 6
      hidden_dims: [48, 24]
      dropout_rate: 0.12

training:
  batch_size: 64
  learning_rate: 0.001
  epochs: 10
  early_stopping: true
  patience: 8
  reduce_lr: true
  validation_split: 0.2

features:
  threshold_percentile: 95
  use_amount_features: true
  use_temporal_features: true
  use_customer_features: true
  use_risk_flags: true

sweep:
  stage: "broad"
  top_k: 3
  output_config: "configs/sweep_narrow.yaml" 