features:
  threshold_percentile: 95
  use_amount_features: true
  use_customer_features: true
  use_risk_flags: true
  use_temporal_features: true
model:
  dropout_rate: 0.2
  hidden_dims:
  - 128
  - 128
  - 64
  - 64
  - 32
  - 32
  latent_dim: 16
seed: 42
sweep:
  epochs:
  - 12
  - 18
  learning_rates:
  - 0.001
  - 0.002
  output_config: configs/final_optimized_config.yaml
  stage: final
  threshold_percentiles:
  - 92
  - 95
  - 98
training:
  batch_size: 64
  early_stopping: true
  epochs: 10
  learning_rate: 0.001
  patience: 15
  reduce_lr: true
  validation_split: 0.2
