seed: 42

model:
  # Will be auto-filled by narrow sweep with best architecture
  latent_dim: 16
  hidden_dims: [128, 64, 32]
  dropout_rate: 0.2

training:
  # Fine-tuning parameters
  batch_size: 64
  learning_rate: 0.001
  epochs: 150
  early_stopping: true
  patience: 20
  reduce_lr: true
  validation_split: 0.2

features:
  threshold_percentile: 95
  use_amount_features: true
  use_temporal_features: true
  use_customer_features: true
  use_risk_flags: true

sweep:
  stage: "final"
  threshold_percentiles: [90, 92, 95, 98]
  learning_rates: [0.0001, 0.0003, 0.001]
  epochs: [100, 150, 200]
  output_config: "configs/final_optimized_config.yaml" 