features:
  threshold_percentile: 95
  use_amount_features: true
  use_customer_features: true
  use_risk_flags: true
  use_temporal_features: true
model:
  architectures:
    deep:
      dropout_rate: 0.2
      hidden_dims:
      - 128
      - 128
      - 64
      - 64
      - 32
      - 32
      latent_dim: 16
    shallow_wide:
      dropout_rate: 0.15
      hidden_dims:
      - 512
      - 256
      - 128
      latent_dim: 8
    xlarge:
      dropout_rate: 0.3
      hidden_dims:
      - 512
      - 256
      - 128
      latent_dim: 32
  dropout_rate: 0.2
  hidden_dims:
  - 128
  - 64
  - 32
  latent_dim: 16
seed: 42
sweep:
  output_config: configs/sweep_final.yaml
  stage: narrow
  top_k: 1
training:
  batch_size: 64
  batch_sizes:
  - 64
  - 128
  dropout_rates:
  - 0.1
  - 0.2
  early_stopping: true
  epochs: 12
  learning_rate: 0.001
  learning_rates:
  - 0.001
  - 0.002
  patience: 15
  reduce_lr: true
  validation_split: 0.2
