_wandb:
    value:
        cli_version: 0.21.0
        e:
            wp254kgx85lcg3bjjez2z9ucbaakm7yj:
                codePath: sweeps\final_model_sweep.py
                codePathLocal: sweeps\final_model_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "11.0"
                disk:
                    /:
                        total: "254855344128"
                        used: "248405557248"
                email: tommywood81@gmail.com
                executable: C:\Users\tommy\projects\auto-encoder-project\env\Scripts\python.exe
                git:
                    commit: 7b3580ff3b78a58ae061be637ef26f06bb092708
                    remote: https://github.com/tommywood81/auto-encoder-project.git
                gpu: GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      name: GeForce GTX 1650
                      uuid: GPU-1fae71aa-5bd3-0913-de7a-02c43e0b27b4
                host: LAPTOP-U7F1NDJK
                memory:
                    total: "34188873728"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\tommy\projects\auto-encoder-project\sweeps\final_model_sweep.py
                python: CPython 3.11.3
                root: C:\Users\tommy\projects\auto-encoder-project
                startedAt: "2025-07-24T22:28:50.118651Z"
                writerId: wp254kgx85lcg3bjjez2z9ucbaakm7yj
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.3
            "5": 0.21.0
            "8":
                - 2
                - 3
            "12": 0.21.0
            "13": windows-amd64
feature_strategy:
    value: combined
hyperparameters:
    value:
        learning_rate: 0.005
        threshold: 99
model_config:
    value:
        activation_fn: relu
        batch_size: 128
        early_stopping: true
        epochs: 50
        latent_dim: 16
        learning_rate: 0.015
        threshold: 99
rank:
    value: 1
roc_auc:
    value: 0.7335672734849135
