_wandb:
    value:
        cli_version: 0.21.0
        e:
            bboheeulc2cyoolcavvz43kcq96na2n3:
                args:
                    - --entity
                    - tommywood81-fractal-dynamics
                codePath: sweeps\sweep_parameters_wandb.py
                codePathLocal: sweeps\sweep_parameters_wandb.py
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "11.0"
                disk:
                    /:
                        total: "254855344128"
                        used: "252684148736"
                email: tommywood81@gmail.com
                executable: C:\Users\tommy\projects\auto-encoder-project\env\Scripts\python.exe
                git:
                    commit: 33911802d998b16157dfe8f623f0e5714d16d0b9
                    remote: https://github.com/tommywood81/auto-encoder-project.git
                gpu: GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      name: GeForce GTX 1650
                      uuid: GPU-1fae71aa-5bd3-0913-de7a-02c43e0b27b4
                host: LAPTOP-U7F1NDJK
                memory:
                    total: "34188873728"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\tommy\projects\auto-encoder-project\sweeps\sweep_parameters_wandb.py
                python: CPython 3.11.3
                root: C:\Users\tommy\projects\auto-encoder-project
                startedAt: "2025-07-10T23:12:52.223151Z"
                writerId: bboheeulc2cyoolcavvz43kcq96na2n3
        m: []
        python_version: 3.11.3
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.11.3
            "5": 0.21.0
            "8":
                - 2
                - 3
            "12": 0.21.0
            "13": windows-amd64
        visualize:
            confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
features:
    value:
        strategy: combined
model:
    value:
        activation_fn: leaky_relu
        batch_size: 128
        epochs: 10
        latent_dim: 8
        learning_rate: 0.001
        threshold: 90
training:
    value:
        early_stopping_patience: 5
        min_delta: 0.001
        reduce_lr_patience: 3
        validation_split: 0.2
wandb:
    value:
        entity: tommywood81-fractal-dynamics
        feature_group: combined_features
        group: hyper-parameter-tuning
        project: fraud-detection-autoencoder
        tags:
            - param_sweep
            - stage_broad
